---
# dependency:
#   name: galaxy
#   options:
#     role-file: molecule/default/requirements.yml
driver:
  name: docker
platforms:
  - name: ansible-role-virtualbox-1604
    image: ubuntu:16.04

lint:
  name: yamllint
  enabled: False

provisioner:
  name: ansible
